### ISSUE TITLE
Question about friendly and native url 

### ISSUE THREAD

**Issue by artmadeit** [Backblaze/b2-sdk-python#105]
Hi,
First thanks for the awesome python sdk

I have one question how do we retrieve the friendly and native URL using this sdk. 

![image](https://user-images.githubusercontent.com/18428325/73700438-8ce38500-46b4-11ea-8e88-39cd3d646806.png)

When I [upload a file](https://b2-sdk-python.readthedocs.io/en/master/quick_start.html#upload-file), i just get a `FileVersionInfo` object, which in the docs doesn't have a friendly or a native url property. 

I think a way to get these URLs is useful if I want to upload a file and link this file (based on these URLs) to a column (for example file_url) in my database.

For now I'm just hardcoding the url with something like: 
```python
response = bucket.upload_bytes() # ....
file_id = response.id_
url = "https://f000.backblazeb2.com/b2api/v1/b2_download_file_by_id?fileId=" + file_id
```

Thanks

**Comment by ppolewicz** [comment]
I think you are looking for [b2sdk.v1.B2Api.get_download_url_for_fileid()](https://b2-sdk-python.readthedocs.io/en/master/api/api.html#b2sdk.v1.B2Api.get_download_url_for_fileid), right?

**Comment by artmadeit** [comment]
That's it! Thanks :)

**Comment by ppolewicz** [comment]
Happy to help @artmadeit. By the way, could you describe what you are doing with the sdk? As we are growing it, the ongoing question is how we can support the users better, so getting an insight of what you do with it would be valuable.

**Comment by artmadeit** [comment]
@ppolewicz Just to upload files (PDF files) generated from a medical device. The medical device send a file to a server (which is on django) and it relates that file, based on the name of it, with a clinical history (stored in a database)

**Comment by ppolewicz** [comment]
Interesting. Did you consider using short-lived write access keys restricted to userid prefix, so that the medical device can upload the PDF file directly to B2, bypassing django?
