### ISSUE TITLE
No public API for getting a list of file ids for a filename

### ISSUE THREAD

**Issue by Mossop** [Backblaze/b2-sdk-python#117]
In order to delete a file you need to know the file id of the version to delete but unless I'm missing something there is no straightforward way to list the different versions of a file with a given filename. `bucket.ls` exists but since it enforces a trailing `/` on the folder you pass the only way I can see right now to get this through the public API is to do something like this:

```python
def get_file_ids(bucket, filename):
    for file_info, folder_name in bucket.ls(folder_to_list=os.path.dirname(filename), show_versions=True):
        if file_info.file_name == filename:
            yield file_info
```

Obviously this potentially wastes bandwidth by returning all files in the same "folder".

**Comment by ppolewicz** [comment]
I agree.

Would (properly implemented) `bucket.list_file_versions(filename)` be an appropriate solution?

**Comment by Mossop** [comment]
Sounds perfect. I think I can see how to implement it so I'll give it a shot.

**Comment by ppolewicz** [comment]
Awesome, let me know if you need any help (with testing on RawSimulator or something)
