### ISSUE TITLE
Feature Request: Generate Presigned URLs

### ISSUE THREAD

**Issue by rdegges** [Backblaze/b2-sdk-python#136]
Hi there.

I'm a new B2 user. I've got files stored in a private B2 bucket and I'd like the ability to be able to generate a download token with a set expiration time that I can give to users so they can temporarily download files from my private B2 bucket.

S3 supports this functionality, and since B2 is API compatible, I believe this should be possible.

Unfortunately, when I try to use the official boto3 library to access B2 and generate a presigned URL for a B2 item, I run into issues. For example:

```python
url = s3.generate_presigned_url('get_object', Params={
    'Bucket': 'BUCKET',
    'Key': 'FILENAME',
}, ExpiresIn=60 * 60 * 24 * 7 # 7 days in seconds
print(url)
```

The resulting URL I get back from this call to B2 looks something like this:

```
https://s3.us-west-002.backblazeb2.com/BUCKET/FILE?AWSAccessKeyId=XXX&Signature=gEPp9je72g01htiu5VZJPMZA344%3D&Expires=1591850644
```

Unfortunately, when I go to visit this URL, I get a B2 authorization error:

```xml
<Error>
  <Code>UnauthorizedAccess</Code>
  <Message>bucket is not authorized: BUCKET</Message>
</Error>
```

This led me to try to use this native B2 library to accomplish this feat instead, but unfortunately, it doesn't appear there is a way to make this work using this library.

It'd be cool to get some support added to generate a presigned file download URL =)

**Comment by ppolewicz** [comment]
This is how you can use the token:

`https://f345.backblazeb2.com/file/photos/cute/kitten.jpg?Authorization=3_20160803004041_53982a92f631a8c7303e3266_d940c7f5ee17cd1de3758aaacf1024188bc0cd0b_000_20160804004041_0006_dnld`
(example from https://www.backblaze.com/b2/docs/b2_download_file_by_name.html)

And here is an sdk function to generate the token: https://b2-sdk-python.readthedocs.io/en/master/api/bucket.html#b2sdk.v1.Bucket.get_download_authorization

**Comment by rdegges** [comment]
Thanks! I was able to re-implement my code to get it working using those methods.

Maybe as a follow-up, it'd be neat if there was a method that could generate the entire signed URL so I don't need to manually assemble it from several different places <3

**Comment by ppolewicz** [comment]
Signed url is one of the ways to access it as you can also use a header to pass the authorization key (and then it won't be logged in GET parameters on a proxy or WAF), so I would say it's a bit more secure, though using an url is very practical. I think this would be a nice addition to b2sdk (and b2cli as well).

This feature is small and easy to test. It was your idea and I think it is meaningful to the b2 ecosystem. Would you like to author a pull request to add it? Then the full credit would go to you and I really think you deserve it.

**Comment by rdegges** [comment]
Sure, let me ask you a question since you've got a lot more experience than I do with the library already:

Should I be hitting the authorize endpoint in real-time before generating one of these authorized download tokens? Or can I rely on that information being cached in advance?

**Comment by ppolewicz** [comment]
We don't cache those tokens, you need to generate a new one, but there is a function `Bucket.get_download_authorization()` for it already, that returns the token. Now you'd want to merge the token with a download by name / id into something that can be easily accessed through the url, so I think we need new optional parameters to `B2Api.get_download_url_for_fileid()`, `B2Api.get_download_url_for_file_name` and `Bucket.get_download_url()`, so that you can pass in the token that you just got from `Bucket.get_download_authorization()` and then the generated link will contain the authorization key in the GET params. +tests and we should be good

**Comment by half-duplex** [comment]
It's nice that the Authorization token can be passed as a query parameter, but it would also be good if the s3 sdk generate_presigned_url URLs worked correctly, both for compatibility and because (aiui) it's completely local rather than requiring an API call to b2.

**Comment by lorandDobai** [comment]
Any updates on this? S3 Presigned urls still return the error:
```
<Error>
    <Code>UnauthorizedAccess</Code>
    <Message>bucket is not authorized: {Bucket}</Message>
</Error>
```
Yes, the native SDK URL authorization way works, but it would be really nice to have standard S3 presigned urls working too, for consistency and compatibility reasons.

**Comment by ppolewicz** [comment]
I don't think `b2-sdk-python` developers can help with this, you should email b2 support to talk to the server team

**Comment by J-Rojas** [comment]
For those who Google and encounter this error with the AWS CLI, the way to resolve this is to make sure your AWS_REGION is set to the correct region from b2. For example: s3.us-west-000.backblazeb2.com would have an AWS_REGION=us-west-000. This will then create a properly presigned url from the cli tool.
