### ISSUE TITLE
Move the test scripts

### ISSUE THREAD

**Issue by ppolewicz** [Backblaze/b2-sdk-python#14]
move `b2sdk/account_info/test_upload_url_concurrency.py` and `test_raw_api`, `test_raw_api_helper`, `_clean_and_delete_bucket`, `_should_delete_bucket`, `_add_range_header` from `b2sdk/raw_api.py` to somewhere else, so that we can still execute them in `pre-commit.sh`, but so that it does not get test coverage tracking and so that it is not shipped in the package to the library user

**Comment by mjurbanski-reef** [comment]
outdated - we don't even use pre-commit.sh anymore; Any reorganization of test code should be done as part of #191  .
