### ISSUE TITLE
Default to a better cache

### ISSUE THREAD

**Issue by phistrom** [Backblaze/b2-sdk-python#144]
https://github.com/Backblaze/b2-sdk-python/blob/b103939cc19020a5f7cae7a6e26f1073b5ba2232/b2sdk/session.py#L67

If the user specifies no AccountInfo object, they get a SqliteAccountInfo and an AuthInfoCache by default. This is a good thing. However, if they specify any other AccountInfo object (InMemoryAccountInfo for instance), they get an even worse cache: the DummyCache.

What could break if at the very least this defaulted to the InMemoryCache at minimum? Personally I don't see the harm of always defaulting to the AuthInfoCache instead. AbstractAccountInfo already forces the implementation of the functions necessary for AuthInfoCache to function correctly. This could only break existing code where people use their own AccountInfo objects that are themselves broken.

**Comment by ppolewicz** [comment]
I agree, though the plan for api v2 is to replace `InMemoryAccountInfo` with `SqliteAccountInfo` using a special `:memory:` "file". Will that, in your opinion, be a good fix?

**Comment by phistrom** [comment]
That sounds great, but for those who remain on v1 (if they set up their requirements.txt file as the docs suggest with `b2sdk>=0.0.0,<1.0.0`), it seems like an easy way to save them a couple of API calls with no harm done.

I truly have no strong opinions either way. I just thought it was worth suggesting.

**Comment by ppolewicz** [comment]
Default is documented to be `DummyCache`, so apiver says we should not change it... unless that was actually a bug and using `DummyCache` for anything other than unit tests makes no sense at all... but even in that case, we don't want to break unit tests for someone if they rely on the fact that it is set to `DummyCache`. I don't think this default should be documented like that, we should be free to change it to something - but it is documented and apiver says we should keep it like it is (for v1). Apiver is a blessing and a curse at the same time, but once we get used to incrementing the interface version, it should become easier.

As for v1 users, I hope they will, one day, go through the trouble of changing their requirements to get new exciting stuff that we will roll out in the coming months. No major breaking changes are planned, but some things should change. The difference between apiver and others is that we don't have to rename the package when we want change the interface of the library.

**Comment by phistrom** [comment]
I did not realize it was documented like that and I totally understand not changing the default. No argument there.
