### ISSUE TITLE
question: how to throttle file transfers?

### ISSUE THREAD

**Issue by sdanieru** [Backblaze/b2-sdk-python#157]
Hello,
I have a python3 application leveraging the b2sdk; how can I throttle bucket.upload_local_file() for example? I'd like to limit to a set bandwidth if possible, say 100Mbps; is that possible?

**Comment by ppolewicz** [comment]
Currently there is no native support in b2sdk to throttle the upload/download speed, but maybe you could use https://github.com/Backblaze/B2_Command_Line_Tool/issues/310#issuecomment-394190491 to limit the entire process. Please see that issue for further discussion of that subject.

Why do you want to limit the bandwidth? Isn't sending things as fast as possible better in your case? Why?

**Comment by sdanieru** [comment]
Hi @ppolewicz, thanks for the response.

The thread you linked is interesting, I'll try `trickle` and see if that gives me the result I'm looking for. I agree with SuperTango's sentiment, namely that it's important a backup or sync solution have the ability to throttle at a specified rate. I'd love to see this functionality in b2sdk.

In my case, the primary impetus is we currently have a commit rate of 100Mbps at our colo; sending our nightly db snapshots to B2 every night at full link speed (1Gbps) is pushing our 95th percentile way too high (read: expensive!) Throttling to ca 100Mbps would be ideal.

**Comment by ppolewicz** [comment]
trickle sounds like a good choice here (or reconfigure the network card to 100Mbps ha ha)

**Comment by sdanieru** [comment]
Looks like I got lucky and trickle is working as intended, so that's good; thanks for the tip!

I still think having throttling functionality in the sdk is important for a tool that sends/receives files to B2 and I hope it gets on your todo list:)

**Comment by ppolewicz** [comment]
Well, it looks like the CPU penalty for managing the throughput in python might be big and the number of users who can't just use `trickle` seems to be close to zero. I think there are some things that this project would benefit more from than throttling.

**Comment by sdanieru** [comment]
I'd like to add here that I was mistaken: trickle seems unable to properly throttle for me: bandwidth usage is close to link speed no matter what value I set for trickle. I'm using python3. That being the case, I'd be surprised if trickle is working for others using b2-sdk-python in python3, whether it is or not, I'd be interested to hear about it.

@ppolewicz If other users are also not succeeding in using trickle for the sdk with python3, you may find the number of users that wants/needs this functionality is much more than 'close to zero'. Again, being able to throttle bandwidth for shuffling files to/from B2 is, in my mind at least, important functionality. I hope the feature merits further consideration from your team. I'd be interested to hear more about your concern about CPU penalty as I obviously know very little about how feasible it would be to implement the functionality.

**Comment by ppolewicz** [comment]
I know it doesn't really solve the problem via feature, but still I hope you can find it useful: I think you can use iptables to throttle per user or per destination. This might be a good idea in general, because if something else on your machine decides to consume bandwidth while you are backing things up, you'd burst through your 95th percentile colo commitment and pay a lot for it
