### ISSUE TITLE
Support Download URLs with CDN

### ISSUE THREAD

**Issue by ehossack** [Backblaze/b2-sdk-python#193]
Hi, I'm looking to use backblaze with cloudflare as suggested here: https://help.backblaze.com/hc/en-us/articles/217666928-Using-Backblaze-B2-with-the-Cloudflare-CDN

One thought I had that might be a clean solution is extending `Session`'s [`authorize_account`](https://github.com/Backblaze/b2-sdk-python/blob/0cd994cf91e321f180795f0df6cf8d74a48d494e/b2sdk/session.py#L94) params to include a CDN url, which could set the `downloadUrl` prefix  to be the CDN url instead of the backblaze url.
This makes the most sense to me because the CDN url is an explicitly configured proxy, so this maps well to when we initialize the account info, even if it's not semantically related to "authorizing" an account.

It seems like a clean way to support the functionality, but I'm curious as to thoughts on whether this is:
a) the right place to set this
b) within the realm of this library

For example with boto3/s3 you can pre-generate a signed url with cloudfront, whereas here the flow would be reconstructing a url after the fact - possible also in s3/cloudfront, but not supported by the library (unless done through origin access identity)

**Comment by ppolewicz** [comment]
I think you can structure your URLs in cloudflare in more than one way, though, right? The bit that rewrites the cloudflare url to b2 url can be implemented in many different ways and so reversing that url (if possible at all! the url rewriting function can be non-reversible) can be done in more than one way.

As far as I heard, S3 has a JWT-like pre-signing functionality where a client can sign a request with a private key and then S3 server can see that the request is signed without actually communicating with the client in the whole process (other than uploading the public key to the cloud once). B2 native interface doesn't have that - here keys are generated by the server.

You can always inherit Session or Bucket and add some features to it that you'll use, but I don't think this is something b2-sdk-python itself should implement.

**Comment by nilayp** [comment]
Nilay from Backblaze here. 

I’ll just clarify that while the B2 API does not support pre-signed URLs, Backblaze B2 does support this functionality via the S3 compatible API. 

I admit we have documented our support for pre-signed URLs that well. We are currently working on new documentation, which will get published shortly. 

Until then- this article on the Cloudflare blog may be helpful? https://blog.cloudflare.com/backblaze-b2-and-the-s3-compatible-api-on-cloudflare/

**Comment by ehossack** [comment]
Good insight, thanks.
