### ISSUE TITLE
Use rounded=True when invoking get_file_mtime

### ISSUE THREAD

**Issue by mlech-reef** [Backblaze/b2-sdk-python#194]
There is a `FIXME` in `sync/folder.py` and another one in `download_dest.py`

From `get_file_mtime` comments:
> Using `round()` is a non-backward-compatible change, as some files which were uploaded with older versions would have newer `mtime` on the destination, thus b2 may fail. The default will be changed in v2.

See also:
#132

**Comment by ppolewicz** [comment]
Actually b2-sdk-java is truncating (in other words flooring or rounding down) to the bottom of the millisecond and they can't change it easily, so we'll do the same and from now on it will become the standard / recommended behavior.

**Comment by mlech-reef** [comment]
We may want to remove TODOs from the code.
