### ISSUE TITLE
Support Server Side Encryption

### ISSUE THREAD

**Issue by malaysf** [Backblaze/b2-sdk-python#203]
B2 released the [server side encryption](https://www.backblaze.com/b2/docs/server_side_encryption.html) feature and should be supported by the python SDK.

There are two new application key capabilities: `readBucketEncryption` and `writeBucketEncryption` which are required to retrieve and update default bucket encryption settings.

The following APIs have changed as well:

- [x] b2_copy_file
- [x] b2_copy_part
- [x] b2_create_bucket
- [x] b2_download_file_by_id
- [x] b2_download_file_by_name
- [x] b2_start_large_file
- [x] b2_update_bucket
- [x] b2_upload_file
- [x] b2_upload_part
- [x] b2_finish_large_file (response)
- [x] b2_get_file_info (response)
- [x] b2_list_buckets (response)
- [x] b2_list_file_names (response)
- [x] b2_list_file_versions (response)
- [x] b2_list_parts (response)
- [x] b2_list_unfinished_large_files (response)

Those marked with `(response)` only have had new fields added to the APIs response. The others include at least request changes and may also include changes in the response.

**Comment by ppolewicz** [comment]
discussion and design in #691

**Comment by ppolewicz** [comment]
discussion and design in https://github.com/Backblaze/B2_Command_Line_Tool/issues/691

**Comment by ppolewicz** [comment]
SSE-B2 and SSE-C support was implemented and released for both b2cli and b2-sdk-python
