### ISSUE TITLE
Subpackages inside test/ are installed.

### ISSUE THREAD

**Issue by WPettersson** [Backblaze/b2-sdk-python#212]
Currently, setup.py specifically does not install the `test` package, but does still install `test.integration`, `test.static`, `test.unit` and so-on for subpackages. This is because setup.py only excludes `test`. The fix is easy (PR incoming), just exclude `test*`.

**Comment by mlech-reef** [comment]
@WPettersson the problem also exists in CLI. I have created Backblaze/B2_Command_Line_Tool#697 to not forget to fix it there as well.
