### ISSUE TITLE
v1.0.0 API structure

### ISSUE THREAD

**Issue by ppolewicz** [Backblaze/b2-sdk-python#24]
It would be more convenient for users if the most-used classes, like B2Api wore available in the top-level package. Some things are internal, some are not, it is very hard to say for the user which things should be used and which shouldn't.

**Comment by mpnowacki-reef** [comment]
@ppolewicz It seems this issue was created before introducing `apiver`, and `apiver` makes it obsolete, right? Since all library users are supposed to use a single `v*` namespace anyway.

**Comment by ppolewicz** [comment]
this was actually done but renamed to v1
