### ISSUE TITLE
version 1.9.0 -- b2sdk.v1.file_version.FileVersionInfoFactory not backwards compatible

### ISSUE THREAD

**Issue by bllfr0g** [Backblaze/b2-sdk-python#261]
Is b2sdk.v1.file_version.FileVersionInfoFactory considered part of the public API?  If so, I think v1.9.0 introduces a non-backwards-compatible change.

In 1.8.0, b2sdk.v1.file_version.FileVersionInfoFactory.from_api_response() was a ClassMethod.  But in 1.9.0 it is now an instance method and requires an instantiation of the FileVersionInfoFactory object in order to be called.

**Comment by mpnowacki-reef** [comment]
`b2sdk.v1.file_version.FileVersionInfoFactory` is not part of the public API - it's not listed as such in the docs. It is used internally, and there are plans to use it in even lower level private API methods, that's why it seems that it will stay private. Do you think it should be public?
