### ISSUE TITLE
Refactor TempDir to use pathlib

### ISSUE THREAD

**Issue by mpnowacki-reef** [Backblaze/b2-sdk-python#284]
also related to https://github.com/Backblaze/B2_Command_Line_Tool/issues/733

**Comment by mjurbanski-reef** [comment]
b2sdk TempDir has been deprecated.

Instead, https://docs.pytest.org/en/7.1.x/how-to/tmp_path.html should be used in tests, and https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryDirectory in production code .
