### ISSUE TITLE
b2sdk.exception.InvalidUploadSource: Invalid upload source: 

### ISSUE THREAD

**Issue by Void-ux** [Backblaze/b2-sdk-python#287]
I'm trying to upload a bytes image, though it doesn't want to accept it: 
`b2sdk.exception.InvalidUploadSource: Invalid upload source: b'RIFF\xb4\x05\x00\x00WEBPVP8 \xa8\x05\x00\x00\xd0,\x00\x9d\x01*\x00\x01\x00\x01>m6\x9aH\xa4&%\xa1$t\x99\x00\xc0\r\x89en\xe1q\xce+\xca\xc5\x80=\xfb]\xff;\xed\xdb\t\xd`

Not too sure how to fix this.

**Comment by ppolewicz** [comment]
[b2sdk.v2.Bucket.upload_bytes](https://b2-sdk-python.readthedocs.io/en/master/api/bucket.html#b2sdk.v2.Bucket.upload_bytes) or manually wrap your data in an UploadSource object and then use [b2sdk.v2.Bucket.upload](https://b2-sdk-python.readthedocs.io/en/master/api/bucket.html#b2sdk.v2.Bucket.upload)
