### ISSUE TITLE
SSLError when using b2sdk, but b2 client on the same machine works ok

### ISSUE THREAD

**Issue by b4d** [Backblaze/b2-sdk-python#294]
Hi!

I have stumbled upon a problem while using duply/duplicity to backup to B2. It has worked until recently.

Running the `authorize_account(u'production', account_id, account_key)` yields:

```
  File "/usr/local/lib/python3.6/dist-packages/b2sdk-1.13.0-py3.6.egg/b2sdk/b2http.py", line 378, in _translate_errors
    raise B2ConnectionError(str(e0))
 b2sdk.exception.B2ConnectionError: Connection error: HTTPSConnectionPool(host='api.backblazeb2.com', port=443): Max retries exceeded with url: /b2api/v2/b2_authorize_account (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))
```

But I can run b2cli from command line without any problems. That should exclude system problems with SSL certificates.

Anything we can do?

b2 command line tool, version 3.1.0
b2sdk b2sdk-1.13.0-py3.6

**Comment by ppolewicz** [comment]
This might be related to https://github.com/Backblaze/B2_Command_Line_Tool/issues/771

I think your python 3.6 environment may be impaired or it might have an old openssl version. I strongly suspect it's not an issue specific to B2 servers, but you'll have trouble connecting to different services from that python version already.

Please upgrade from 3.6 already - it's EOL in 15 days and we will be dropping support for it very soon.

**Comment by ppolewicz** [comment]
3.6 is no longer supported
