### ISSUE TITLE
Custom sync policy?

### ISSUE THREAD

**Issue by retorquere** [Backblaze/b2-sdk-python#296]
Is there a way to create a custom sync policy? I want to keep some files in the bucket unchanged even though the local counterpart has these files with a newer timestamp. I've tried with exclude regexes but that will treat the excluded files as missing and deletes them in the bucket.

**Comment by ppolewicz** [comment]
Sure, you need to implement this interface: https://github.com/Backblaze/b2-sdk-python/blob/9ed5b69df2d0fc997b54bbdce756392ce082d449/b2sdk/sync/policy_manager.py#L17

and then you need to feed it into the sync. Sync was designed to be customizable so it shouldn't cause you much trouble. Let us know how it works out for you, or please ask if you run into trouble. Also, please observe that you can easily write fast tests using `raw_simulator`. This way you can write the testcase first and then once you have it running (on stock SyncPolicyManager) and failing, you can adjust the code and see it pass the tests when you are done.

**Comment by retorquere** [comment]
And then I'd have to create a custom sync policy class to instantiate and return from `get_policy`, right? Which inherits from AbstractFileSyncPolicy?

The policy I need is probably simple:

* there's a list of files that always get copied from source to target ("replace or create" list)
* there's a list of files that exist both in source and target but which must not be copied from source to target (the timestamps may be off, but I know they're the same, "keep" list)
* any files that exist in the target but not in the source, delete in the target.

**Comment by ppolewicz** [comment]
I think you can use the existing policies, you'd just decide differently than the original synchronizer which policy to use. You can even inherit from `SyncPolicyManager` and do something in cases you care about, but if the case doesn't match your specific pattern,
```python3
    return super().get_policy(
        sync_type,
        source_path,
        source_folder,
        dest_path,
        dest_folder,
        now_millis,
        delete,
        keep_days,
        newer_file_mode,
        compare_threshold,
        compare_version_mode,
        encryption_settings_provider,
    )
```
to do whatever the standard synchronizer would do in those other cases.

**Comment by retorquere** [comment]
I don't understand. Is get_policy called per filename? What's the point where in intervene?

**Comment by ppolewicz** [comment]
It is called for every filename, yes.

I don't understand the second question.

**Comment by retorquere** [comment]
I thought a policy spanned all files in the sync. It seems I got that wrong -- `get_policy` is called per file-pair, and returns a policy object which implements some methods that decide what needs to be done with *this pair*. Which methods must this policy object implement?

**Comment by ppolewicz** [comment]
All the policy objects you need are already implemented (maybe with an exception of a "do nothing" policy). Click [here](https://github.com/Backblaze/b2-sdk-python/blob/9ed5b69df2d0fc997b54bbdce756392ce082d449/b2sdk/sync/policy.py#L222) to see an example policy (if you really want to go this way). Upwards from that line is the abstract object and it only has one abstract method.

**Comment by retorquere** [comment]
Ah OK, so my policy manager only needs to pick the right one! Got it. Yeah my needs are pretty niche -- I'm maintaining a deb repo in a bucket and I need all files locally to rebuild it, but I don't need to upload the unchanged files.

**Comment by ppolewicz** [comment]
I think in your case `.deb` files have different names for different versions, so `b2 sync --compareVersions none` would assume the files are exactly the same by just looking at the file name (not checking size, not checking mod time, not checking contents - just the file name). This mode is already supported in b2-sdk-python and in cli.

**Comment by retorquere** [comment]
The thing is any non-deb file must always be updated.

**Comment by ppolewicz** [comment]
Yes, you can run the sync process twice, once excluding everything non-Deb
with --excludeRegex and then again for deb files only

**Comment by retorquere** [comment]
I must have done this wrong then previously. Excluded files are not touched at all, rather than being treated as absent? I thought that's what I saw. But if this two-stage sync should work, that's great.

**Comment by ppolewicz** [comment]
I think it should be possible as it is. If it's not, then perhaps b2cli should be adjusted to support it. If it won't work for you, please file an issue in b2cli repo with reproduction scenario.

**Comment by retorquere** [comment]
> you can easily write fast tests using `raw_simulator`. This way you can write the testcase first and then once you have it running (on stock SyncPolicyManager) and failing, you can adjust the code and see it pass the tests when you are done.

Is there documentation or sample code for this?

**Comment by ppolewicz** [comment]
I suggest you look at this: https://github.com/Backblaze/b2-sdk-python/blob/900df6b6921692cc8bc812c5d199b5989bdefcef/test/unit/bucket/test_bucket.py#L181 and other tests which inherit it

**Comment by retorquere** [comment]
I found that, but I don't see how that interacts with a custom policy manager.

**Comment by retorquere** [comment]
I suppose I must somehow pass this to `sync_folders`? I really can't make sense of how this all hangs together. Would it be possible to provide me with a scaffold that does policy selection and bucket emulation? I can probably take it from there.

**Comment by retorquere** [comment]
I don't really understand what's being said here. I should piece it together by taking the B2 CLI and stripping that until it does what I need? I already find it difficult to see the coordinated parts, the full B2 CLI will be more complex no?

**Comment by ppolewicz** [comment]
Ah, I know what's up. Synchronizer class has a bug which prevents users from easily replacing the policy manager. I'll try to fix it next week.

**Comment by ppolewicz** [comment]
@retorquere review #305 please, there is an example in a test now

**Comment by retorquere** [comment]
Given that this is a PR, how can I test this?

**Comment by ppolewicz** [comment]
git clone git@github.com:Backblaze/b2-sdk-python.git

**Comment by ppolewicz** [comment]
```
git clone git@github.com:Backblaze/b2-sdk-python.git
cd b2-sdk-python
git checkout sync_customizability
pip install .
```

**Comment by retorquere** [comment]
I'm trying to forge the testcase into a standalone script, but I'm once again stuck. With this

```
from b2sdk.sync.policy import UpPolicy
from b2sdk.sync.action import B2DownloadAction, B2UploadAction, B2CopyAction, AbstractSyncEncryptionSettingsProvider, UploadSourceLocalFile
from b2sdk.sync.policy_manager import SyncPolicyManager

def assert_folder_sync_actions(self, synchronizer, src_folder, dst_folder, expected_actions):
  """
  Checks the actions generated for one file.  The file may or may not
  exist at the source, and may or may not exist at the destination.
  The source and destination files may have multiple versions.
  """
  actions = list(
    self._make_folder_sync_actions(
      synchronizer,
      src_folder,
      dst_folder,
      TODAY,
      self.reporter,
    )
  )
  assert expected_actions == [str(a) for a in actions]

class MySyncPolicyManager(SyncPolicyManager):
  def get_policy_class(self, sync_type, delete, keep_days):
    return UpPolicy

synchronizer = synchronizer_factory(
  compare_version_mode=CompareVersionMode.SIZE,
  keep_days_or_delete=KeepOrDeleteMode.DELETE,
  sync_policy_manager=MySyncPolicyManager(),
)
src = folder_factory('local', ('a.txt', [200], 11))
dst = folder_factory('b2', ('a.txt', [100], 10))
# normally_expected = [
#     'b2_upload(/dir/a.txt, folder/a.txt, 200)',
#     'b2_delete(folder/a.txt, id_a_100, (old version))'
# ]
expected = ['b2_upload(/dir/a.txt, folder/a.txt, 200)']
self.assert_folder_sync_actions(synchronizer, src, dst, expected)
```

I do not know where to get synchronizer_factory, and I also don't see where the raw_simulator comes in.

Is there really no documentation from which I could get a sense of what concepts are used and how they hang together (not api docs; api docs are for referral when I already know broadly how things work). I feel pretty shitty about asking for what I fear will just boil down to "implement this for me", but things are just not clicking at all for me.

**Comment by ppolewicz** [comment]
There is a classification of documentation types here: https://documentation.divio.com
I think we do have a tutorial, a little bit of how-to-guide and a reference but we are short on the explanation side.

There are two things you need to do, lets do the customization first and once that works, lets move onto running things on a simulator.

Wehn using the version from the branch, you can pass a `sync_policy_manager` keyword argument to the constructor of `Synchronizer`. When you do that, it will use that custom policy manager instead of the default. If my understanding is correct, this is what you wanted to do, right?
Does it work for you?

**Comment by retorquere** [comment]
Yes, this works.

**Comment by retorquere** [comment]
How does the b2sdk decide on the sync_type?

> Sure, you need to implement this interface:
> 
> https://github.com/Backblaze/b2-sdk-python/blob/9ed5b69df2d0fc997b54bbdce756392ce082d449/b2sdk/sync/policy_manager.py#L17

When I copy this class verbatim as a start for a policy manager, I get

```
AttributeError: 'RepoPolicyManager' object has no attribute 'exclude_all_symlinks'
```

**Comment by ppolewicz** [comment]
Do not mistake SyncPolicyManager with ScanPolicyManager

**Comment by retorquere** [comment]
My current state is at https://gist.github.com/8895e20ea17afc14ec55cad441e8887c

**Comment by retorquere** [comment]
Wait what does the scan manager do then?

**Comment by ppolewicz** [comment]
`ScanManager`  decides which files (and file versions) to care about - you can only sync .mp3 files, for example, if that's what you wish and `ScanManager` performs the filtering for you.

Line 106 should be `sync_policy_manager = RepoPolicyManager()`, not `policies_manager = RepoPolicyManager()`

**Comment by retorquere** [comment]
Oh interesting - why not just have the policy manager return a NoOpPolicy for files that we don't want to deal with rather than a separate manager?

**Comment by ppolewicz** [comment]
because ScanPolicyManager may skip over directories it doesn't want to handle and in your design it would have to emit a NoOpPolicy for every single file version in there (and there may be millions of file versions this sync operation should not care about)

**Comment by retorquere** [comment]
Got it. I think I have it [working](https://github.com/retorquere/zotero-deb/blob/master/custom.py)! So, how to add the simulator?

**Comment by retorquere** [comment]
> because ScanPolicyManager may skip over directories it doesn't want to handle and in your design it would have to emit a NoOpPolicy for every single file version in there (and there may be millions of file versions this sync operation should not care about)

Just as a point of curiosity -- wouldn't a `NoOpPolicy` for the folder passed to get_policy do that? Not contesting the scan manager, just curious.

**Comment by ppolewicz** [comment]
Maybe it could be implemented your way. I actually prefer the current implementation because it keeps the policy decisions and the scan filtering in separate classes - merging those would create a big class that would be harder to work with.

You should try something like
```py
api = B2Api(
    account_info, api_config=B2HttpApiConfig(_raw_api_class=RawSimulator)
)
```

**Comment by retorquere** [comment]
> Maybe it could be implemented your way. I actually prefer the current implementation because it keeps the policy decisions and the scan filtering in separate classes - merging those would create a big class that would be harder to work with.

Fair enough.
 
> You should try something like
> 
> ```python
> api = B2Api(
>     account_info, api_config=B2HttpApiConfig(_raw_api_class=RawSimulator)
> )
> ```

I can do that but I'm not sure what this changes about the behavior. If there's a simulator I assume I can feed it pseudo-files to mimic the actual behavior?

**Comment by ppolewicz** [comment]
it's a cloud-in-ram, so please don't upload large files or you'll run out of memory. You can create a local directory with some files and you can sync it to the fake api, then inspect to see if it synced the files you wanted to sync and that it didn't sync the files you didn't want to sync. You can then modify the local directory and run the sync again, and inspect again - without waiting for a latency for communication with a cloud on the other side of the internet, so way faster. To ensure b2-sdk-python quality we run hundreds of tests using the simulator in seconds, while a few dozen tests on a real cloud (which we run in b2 cli extended test suite) can take several minutes.

**Comment by retorquere** [comment]
Since my sync is purely filename-based, a single character will do the job for the prupose of tests. But I meant how do I set up this raw api to achieve what you explain. Surely there must be some way to pre-populate this sim before I run the test, but I don't see how that one line can do that.

There are some files that I always want to deem different (and so the files in the bucket are always replaced), regardless of timestamps or filesize. If I use `CompareVersionMode.NONE` and `NewerFileSyncMode.REPLACE`, does that give me this outcome?

**Comment by ppolewicz** [comment]
You can upload the files to the fake bucket the same way you upload files to the real bucket.

I don't think `CompareVersionMode.NONE` will do the trick for you. Not sure why you would upload a file again if it has the same name, size and hash as an existing one in the cloud?

**Comment by retorquere** [comment]
> You can upload the files to the fake bucket the same way you upload files to the real bucket.

OK. I thought I could pre-populate it as a known-good state for the actual test. This will work, I'll get on it.

> > I don't think `CompareVersionMode.NONE` will do the trick for you.

But then how do I indicate "when trying to sync the file Packages, assume it to be newer even if the timestamp of the file is older than the one in the bucket".

I have two "kinds" of files in the bucket:
* `.deb` packages, where the bucket object is considered newer if it exists, regardless of timestamps, never overwrite.
* all other files are metadata like `Packages`, and if that differs, regardless of timestamps, always overwrite

> Not sure why you would upload a file again if it has the same name, size and hash as an existing one in the cloud?

I didn't know it also checked the hash. The file size isn't a sufficient check because that can be the same while the contents is not, in which case I'd want to upload again. A hash would do that. That's automatic?

**Comment by ppolewicz** [comment]
Comparison by hash is default, yes (for reasonably "small" files, at least, B2 supports multi-terrabyte objects and those are handled a bit differently)

**Comment by retorquere** [comment]
All non .deb files are miniscule. So [this](https://gist.github.com/8d29009373ccf6dffc873f1c3ab87fbc) would do it then? Or no? The debs are some 50-70MB, would that trigger a hash check? That would be perfect actually; a hash mismatch should always mean a re-upload, regardless of the filetype.

That would work as a general rule for me; just don't look at the file times, only look at the hashes.

**Comment by retorquere** [comment]
Waaaait.... "sync folder -> bucket, don't look at the file times, only look at the hashes" sounds like something the command line b2 client could do by default maybe?

**Comment by ppolewicz** [comment]
Actually default configuration of sync, I think, checks the timestamps and maybe sizes, not hashes. If you'd like there to be a setting which will verify the hash even if the size and timestamp are the same, please submit a pull request. This is not a good default because usually file modification time is a reliable indicator of a file being changed in any way, but it can be an option, why not.

**Comment by retorquere** [comment]
OK but then we have the problem that I don't yet know what combination of settings gets me that behavior :D, because you said

> I don't think `CompareVersionMode.NONE` will do the trick for you. 

I figured `CompareVersionMode.NONE` meant "filename only", then when you explained about the hash I figured it was filename + hash, now I just don't know. But "filename + hash, regardless of timestamp, and overwrite the cloud version if the hashes differ; delete all that are not in the local folder" is what I need for all files I now realize. But I don't know how to do that. I see `CompareVersionMode` can be `MODTIME` (don't want that), `SIZE` (but if the hash is already checked, why bother with the size check), and `NONE` (which I took to be "except hash checks, which always happen").

**Comment by ppolewicz** [comment]
I was wrong. There is no `CompareVersionMode` that would check the hash... yet. It can be added to enum and [here](https://github.com/Backblaze/b2-sdk-python/blob/900df6b6921692cc8bc812c5d199b5989bdefcef/b2sdk/sync/policy.py#L111) though.

**Comment by retorquere** [comment]
So... best option I currently have then is use `NONE`?

**Comment by retorquere** [comment]
How do I set timestamps in the raw simulator?

**Comment by retorquere** [comment]
I've been going throug the sdk sources to see what I could add to `files_are_different` but I don't see anything hashing-related I could use for this.

would this work, assuming `deb` is `True` iff the file under consideration is one that I never want to replace, and when false, I always want to replace:

```
NewerFileSyncMode.SKIP if deb else NewerFileSyncMode.REPLACE, # newer_file_mode
...
CompareVersionMode.NONE if deb else CompareVersionMode.MODTIME, # compare_version_mode
```

**Comment by retorquere** [comment]
> I was wrong. There is no `CompareVersionMode` that would check the hash... yet. It can be added to enum and [here](https://github.com/Backblaze/b2-sdk-python/blob/900df6b6921692cc8bc812c5d199b5989bdefcef/b2sdk/sync/policy.py#L111) though.

The only place where I see something related to upload check for hashes is in transfer/emege.executor.py.

**Comment by ppolewicz** [comment]
What I'm suggesting is that you add `CompareVersionMode.SHA1`, which will determine that the files are different if their size is different, but if the size is the same, checksum of both the source and destination will be compared to see if the files are really exactly the same. The cloud file version will have a sha1 already and on the local one you'll have to read the file and compute the hash (there should be something in utils for it). At least you'll save the transfer.


> How do I set timestamps in the raw simulator?

I don't think it's officially supported, because the cloud interface doesn't support that either. You can upload files, sleep a second and upload again though. You may look at how existing tests of sync are done (perhaps they use freezegun?)

**Comment by retorquere** [comment]
Computing the sha1 hash for the input files is easy, and I already have them at hand for generating the debs, but I don't know how to get the sha1 hash of the remote file on b2

**Comment by retorquere** [comment]
> Computing the sha1 hash for the input files is easy, and I already have them at hand for generating the debs, but I don't know how to get the sha1 hash of the remote file on b2

Wait, is that just the `content_sha1` property?

**Comment by retorquere** [comment]
I'm not getting any deletes in `get_policy` for files that do not exist locally but do exist in the bucket.

**Comment by ppolewicz** [comment]
This patch breaks `CompareVersionMode.SIZE` and the sha1 for any file we already have, I think, in utils.

Which direction are you running the sync? Up to the cloud or down from the cloud?

**Comment by retorquere** [comment]
> This patch breaks `CompareVersionMode.SIZE` and the sha1 for any file we already have, I think, in utils.

Does it? Where did I go wrong?

> Which direction are you running the sync? Up to the cloud or down from the cloud?

Up to the cloud.

**Comment by retorquere** [comment]
I'm currently using this:

```
class RepoPolicyManager:
  """
  Policy manager; implement a logic to get a correct policy class
  and create a policy object based on various parameters.
  """

  def get_policy(self, sync_type, source_path, source_folder, dest_path, dest_folder, now_millis, delete, keep_days, newer_file_mode, compare_threshold, compare_version_mode, encryption_settings_provider):
    """
    Return a policy object.
    :param str sync_type: synchronization type
    :param b2sdk.v2.AbstractSyncPath source_path: source file
    :param str source_folder: a source folder path
    :param b2sdk.v2.AbstractSyncPath dest_path: destination file
    :param str dest_folder: a destination folder path
    :param int now_millis: current time in milliseconds
    :param bool delete: delete policy
    :param int keep_days: keep for days policy
    :param b2sdk.v2.NewerFileSyncMode newer_file_mode: setting which determines handling for destination files newer than on the source
    :param int compare_threshold: difference between file modification time or file size
    :param b2sdk.v2.CompareVersionMode compare_version_mode: setting which determines how to compare source and destination files
    :param b2sdk.v2.AbstractSyncEncryptionSettingsProvider encryption_settings_provider: an object which decides which encryption to use (if any)
    :return: a policy object
    """

    #print( sync_type,  delete, source_folder,                              source_path)
    #       local-to-b2 False   LocalFolder(/Users/emile/github/debs/repo)  LocalSyncPath('InRelease', 1642160794155, 2153)
    assert sync_type == 'local-to-b2', sync_type
    deb = source_path is not None and Path(source_path.absolute_path).suffix == '.deb'
    policy = UpAndDeletePolicy if delete else UpPolicy
    print(source_path, 'deb' if deb else 'other', 'delete' if delete else 'add', policy.__name__)
    return policy(
      source_path,
      source_folder,
      dest_path,
      dest_folder,
      now_millis,
      keep_days,
      NewerFileSyncMode.SKIP if deb else NewerFileSyncMode.REPLACE, # newer_file_mode
      compare_threshold,
      CompareVersionMode.NONE if deb else CompareVersionMode.MODTIME, # compare_version_mode
      encryption_settings_provider,
    )

...

    synchronizer = Synchronizer(
      max_workers=multiprocessing.cpu_count(),
      policies_manager = ScanPoliciesManager(exclude_all_symlinks=True), # object which decides which files to process
      sync_policy_manager = RepoPolicyManager(), # object which decides what to do with each file (upload, download, delete, copy, hide etc)
      dry_run=False,
      allow_empty_source=True,
    )

    no_progress = False

    with SyncReport(sys.stdout, no_progress) as reporter:
      synchronizer.sync_folders(
        source_folder=self.source,
        dest_folder=self.target,
        now_millis=int(round(time.time() * 1000)),
        reporter=reporter,
      )

```

but not only do I not get deletes, I'm accumulating versions while the bucket policy is

>  File Lifecycle: Keep only the last version

**Comment by retorquere** [comment]
If I `ls` a bucket with `latest_only=True`, how do I know between duplicates which is the latest (so that I can delete the others to clean up)

**Comment by ppolewicz** [comment]
you might have forgotten to pass a `--delete` flag - without it remote objects not present on the source will not be deleted.

In order to make sure you didn't break anything, you can just run our unit tests. Please see the docs on how to do that, it should clearly say. You should also add tests for the new feature that you are adding to make sure it works correctly and to make sure it stays that way after other contributors modify it in the future.

Lifecycle rules are applied once per day.

**Comment by ppolewicz** [comment]
This is now moving a little bit beyond b2-sdk-python support ;)

> I'm running this from my own code, not the CLI, I don't know where I should add this to the synchronizer

Please see the docs of Synchronizer constructor.

> I'd really love to but I don't know how to fetch the remote hash. Or is that already done? Or how to add it to the local file object.

As you pointed out yesterday, it's `fileversion.content_sha1`

> > Lifecycle rules are applied once per day.
> 
> That's good to know. So what happens when they kick in? Are old versions removed automatically?
> 
> Does that mean the first day of use buckets always collect versions?

Please see B2 documentation of lifecycle rules, no point in me copypasting it here. You probably want sync to delete data immediately though, so set up the Synchronizer for it when creating its object.

**Comment by retorquere** [comment]
> This is now moving a little bit beyond b2-sdk-python support ;)

Fair enough.

> Please see the docs of Synchronizer constructor.

👍 . I was getting a little overwhelmed so I spent less time in the docs than I should have.

> 
> > I'd really love to but I don't know how to fetch the remote hash. Or is that already done? Or how to add it to the local file object.
> 
> As you pointed out yesterday, it's `fileversion.content_sha1`

Right, but if that's available, why wouldn't the above patch work?

> Please see B2 documentation of lifecycle rules, no point in me copypasting it here. You probably want sync to delete data immediately though, so set up the Synchronizer for it when creating its object.

Fair enough again, but I took https://www.backblaze.com/b2/docs/lifecycle_rules.html to mean that it would check the b2-initiated rules (by something like cron) to be ran once a day. I figured that things that are directly related to an activity initiated on a bucket like performing an upload would just directly check whether eg files should be deleted.

**Comment by retorquere** [comment]
> I think your patch causes sha1 calculation of all source files of matching size even if `CompareVersionMode.SIZE` is the selected mode.

Got it.
 
> As for checking whether it will work or not, I suggest that you add a test. This really is a good way, because the test stays in the source code and provides quality assurance with no additonal effort (as opposed to manual testing and then providing test automation).

I fully support test-everything but if something was obviously broken I just preferred to get to that first; otherwise I wouldn't have known whether the test addressed the breakage at all.

**Comment by retorquere** [comment]
When I run

```
B2_TEST_APPLICATION_KEY_ID=x B2_TEST_APPLICATION_KEY=y nox -s test-3.10
```

on the `sync_customizability` branch as-is (so without any changes by me), I get

```
E           Failed: test_raw_api failed
```

I'd prefer it to have the tests running green before my addititions or adding new tests. What should I be doing differently?

**Comment by ppolewicz** [comment]
that depends on the full output of `nox`. CI passed and that tests passes for me locally.

Generally this thread shows that you should dig a little bit deeper by yourself (see the log, check documentation, self-review) - otherwise you'll constently get blocked awaiting for another contributor to help you.

**Comment by retorquere** [comment]
I can fully understand that I'm taking an inordinate amount of your time -- that also worries me, I feel really shitty about this taking so much time, but I *have* looked into these things and I keep getting stuck. The Contributors Guide does not say how to run the tests beyond the two `nox` calls, and it is really surprising to me that the test suite doesn't run green by default when I literally run `nox -s test-3.10` as it says on a freshly cloned repo.

**Comment by ppolewicz** [comment]
it runs green for me.

The key that you've used has capabilities: `deleteFiles,shareFiles,writeBucketEncryption,readFiles,writeFiles,listBuckets,listFiles,readBuckets,readBucketEncryption` and is restricted to bucket `zotero-test`. This is not enough to run integration tests.

**Comment by retorquere** [comment]
I'll create a key with all permissions. I'll just tinker until I get it to work.
