### ISSUE TITLE
Upload from a remote source?

### ISSUE THREAD

**Issue by pljspahn** [Backblaze/b2-sdk-python#300]
I have files stored on a remote web server that I would like to upload to a bucket but I don't want to have to download those files locally first. I'd like the transfer to go from my remote source directly to the bucket, as where I am working from has limited bandwidth and the total transfer size would take ages and setting up a new server to run this code instead of being able to run locally complicates things.

I see the references in the documentation for `bucket.create_file()` but I'm not seeing an argument for declaring the remote source and there aren't any examples provided. It looks like I can only copy from file in an existing bucket and not from an arbitrary remote source?

I guess, ultimately, the question is, does B2 support an interface that can fetch/download files when supplied with a url?

Such as:
```
bucket = b2_api.get_bucket_by_name('my-bucket')
url = 'https://www.mysite.com/images/my_image.jpg'
# This would trigger the B2 server to go and fetch the file itself
bucket.fetch_from_remote(url, 'my-new-file-name')
```

**Comment by ppolewicz** [comment]
The server API does not support a remote fetch and thus b2-sdk-python doesn't support it either.

What I could recommend is a vultr.com server (set up using [this instruction](https://help.backblaze.com/hc/en-us/articles/4406495825051-How-to-setup-Vultr-Compute-with-Backblaze-B2) for good effect) - it will save you a ton of money on the transfer.

If you really have a lot of data, maybe you can talk to B2 sales team and do a reverse fireball or something.

**Comment by pljspahn** [comment]
It's not such an extreme amount of data that I would need to do a fireball (it's probably around 15-20k images, many of which are jpeg that got originally saved at quality 100), rather this is a rural business with few ISP options and none of them are good. Bogging down our limited bandwidth with file transfers can affect our other employees and other devices (like credit card machines) and that's best avoided.

I suppose I'll set up a cloud server to handle the bulk of the transfers.

**Comment by ppolewicz** [comment]
You can run b2 cli via `trickle` to limit the bandwidth consumption, or you can put it all on a big drive and plug that drive for upload somewhere with a good internet connection
