### ISSUE TITLE
lifecycle_rules dict vs. list

### ISSUE THREAD

**Issue by hyperknot** [Backblaze/b2-sdk-python#319]
There is an issue with lifecycle_rules. The docs is expecting a dict, the source code is expecting a dict. However the server is actually expecting a list. If sending a dict at bucket creation or update, the server returns:
```
b2sdk.exception.BadRequest: array should start with bracket but found: { (bad_request)
```

With list it works. I believe all the source code and documentation has to be updated to list.

**Comment by ppolewicz** [comment]
Nice finding! Would you like to contribute a fix?

**Comment by hyperknot** [comment]
No, I just wanted to report it.

**Comment by ppolewicz** [comment]
it's just an error in the documentation, it actually works if you pass the right dict into it. I'll fix it.

**Comment by hyperknot** [comment]
It definitely didn't work with dict, I get the error.

**Comment by ppolewicz** [comment]
I mean that if you pass it a list, then it works correctly - it's just that the type on the signature is misleading.

**Comment by hyperknot** [comment]
I mean my IDE was making a warning around it, as it's doing the type checkings internally. If the docs are auto-generated from the type hints then I guess you've also fixed that one.
