### ISSUE TITLE
Remove hard dependency from tqdm

### ISSUE THREAD

**Issue by ppolewicz** [Backblaze/b2-sdk-python#387]
https://github.com/Backblaze/b2-sdk-python/blob/56c82aa14a918bcd89470e32c84744d737edf9b8/requirements.txt#L5

b2-sdk-python relied on tqdm but it actually doesn't need it and tolerates the absence, but most b2-sdk-python users don't use tqdm, it's only the CLI users that do. Therefore this dependency should be moved to CLI.

**Comment by miketheman** [comment]
Completed in https://github.com/Backblaze/B2_Command_Line_Tool/pull/873 and released as version 3.9.0

tqdm can now be removed from the SDK.

**Comment by miketheman** [comment]
Hi there! This was closed, but the dependency remains in the requirements file, is that expected?

**Comment by ppolewicz** [comment]
There is a [PR](https://github.com/Backblaze/b2-sdk-python/pull/393) to address this, discussion will move there, I might have clicked close too early. There is a discussion about version compatibility, we might need to increase major version as someone can depend on sdk installing tqdm.
