### ISSUE TITLE
Refactor path handling code to use pathlib instead of strings

### ISSUE THREAD

**Issue by przadka** [Backblaze/b2-sdk-python#391]
In various parts of our codebase, we are handling paths as string objects. It is recommended to use the pathlib module when dealing with paths as it provides a more readable and reliable way to handle filesystem paths. It also makes the code more object-oriented and less error-prone.

Here is an example of the current code that should be refactored:

```python
def fix_windows_path_limit(path):
    """
    Prefix paths when running on Windows to overcome 260 character path length limit.
    See https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#maxpath

    :param path: a path to prefix
    :type path: str
    :return: a prefixed path
    :rtype: str
    """
    if platform.system() == 'Windows':
        if path.startswith('\\\\'):
            # UNC network path
            return '\\\\?\\UNC\\' + path[2:]
        elif os.path.isabs(path):
            # local absolute path
            return '\\\\?\\' + path
        else:
            # relative path, don't alter
            return path
    else:
        return path
```

The following classes and methods are known to require this refactor:

- `def fix_windows_path_limit(path)`
- `class AbstractFolder` and its subclasses
- `class ProgressReport` (potentially)
- `class AbstractPath` and its subclasses
- `class ScanPoliciesManager`
- `class AbstractAction` and its subclasses

This issue's resolution would involve replacing the current string path handling with pathlib objects, ensuring all related functionality remains intact.

**Comment by mjurbanski-reef** [comment]
better described, but still a duplicated of #239
