### ISSUE TITLE
some directory exclusion patterns that worked in 1.21.0 don't work in 1.22.0

### ISSUE THREAD

**Issue by titus8** [Backblaze/b2-sdk-python#407]
Consider a folder root directory `"foo"` containing a subdirectory `"bar"`. In `1.21.0`, the exclusion regex `"bar$"` successfully excludes `"bar"`. In `1.22.0`, the exclusion regex must be `r"\./bar$"`.

The reason for this has to do with the pathlib changes for `1.22.0`.

At `b2sdk-1.21.0/b2sdk/scan/folder.py:221`, we have `relative_dir_path = ""`, resulting in `relative_file_path = "bar"`.

In the equivalent code at  `b2sdk-1.22.0/b2sdk/scan/folder.py:251`, we have `relative_dir_path = Path("")`, which results in `str(relative_dir_path) = "."`, and `relative_file_path = "./bar"`.

**Comment by ppolewicz** [comment]
Thank you for a detailed bug report. This is fixed by #408 and b2sdk `1.22.1` with the fix will has been released.
