### ISSUE TITLE
passing compiled regex results in AttributeError

### ISSUE THREAD

**Issue by titus8** [Backblaze/b2-sdk-python#421]
I am using b2sdk-1.24.0.

`b2sdk.v2.ScalPoliciesManager` accepts `Iterable[str | re.Pattern]` for `exclude_dir_regexes`. However, if `exclude_dir_regexes` contains an `re.Pattern` instance, an Attribute error results at `b2sdk/scan/policies.py:70` because `re.Pattern has no attribute 'endswith'`. When regex is `re.Pattern`, `regex.pattern.endswith` must be used.

**Comment by ppolewicz** [comment]
Hi @titus8,

thank you for the detailed bug report. It seems that you've done most of the work required to fix it - would you like to add the `if` statement yourself to complete the PR?
