### ISSUE TITLE
large file missing key ID

### ISSUE THREAD

**Issue by titus8** [Backblaze/b2-sdk-python#422]
In b2sdk-1.24.0/doc/source/server_side_encryption.rst:

_In applications requiring enhanced security, using unique key per file is a good strategy. **b2sdk** follows a convention,
that makes managing such keys easier: `EncryptionSetting` holds a key identifier, aside from the key itself. This key
identifier is saved in the metadata of all files uploaded, created or copied via **b2sdk** methods using `SSE-C`,
under `sse_c_key_id` in `fileInfo`. This allows developers to create key managers that map those ids to keys, stored
securely in a file or a database._ 

However, I’m seeing a problem with some files that B2 designates as large, and that are encrypted with SSE-C. The key ID is missing from file_info

`{'src_last_modified_millis': '1645044242000', 'large_file_sha1': '8013b77a3b3f5327c88524bcd3ff20fb79affc42'}`

and from the encryption setting

`<EncryptionSetting(EncryptionMode.SSE_C, EncryptionAlgorithm.AES256, <EncryptionKey(None, None)>)>
`

Am I missing something here, or is this a bug?

Thanks in advance for your advice. In the meantime, I will investigate further.

**Comment by ppolewicz** [comment]
The response you are getting from the upload call is based on the response of the server which does not send us the key back, therefore the key value of the response is `None`, which means "unknown".

`sse_c_key_id` not being saved in large files sounds like a bug. Will look into it!

**Comment by jsuchan-reef** [comment]
@titus8 I cant replicate it. Can you please provide steps how to reproduce it? Thanks.

**Comment by jsuchan-reef** [comment]
> Did the fix in b2sdk-1.24.1 fix an issue with key_id missing from a large file upload?

yes
