### ISSUE TITLE
sync fails when encryption settings provider returns write mode b2sdk.v2.SSE_NONE

### ISSUE THREAD

**Issue by titus8** [Backblaze/b2-sdk-python#435]
Good Day to All.

I'm using b2sdk-1.24.1. I've found a synchronization failure when an encryption settings provider returns write mode `b2sdk.v2.SSE_NONE`.

A repro script is attached.
[bug.txt](https://github.com/Backblaze/b2-sdk-python/files/13330332/bug.txt)

A traceback is attached.
[traceback.txt](https://github.com/Backblaze/b2-sdk-python/files/13330341/traceback.txt)

It looks like the server is complaining.

Thanks for your attention.

titus8

**Comment by jsuchan-reef** [comment]
Hi,
thanks for the report and the provided code/traceback. I'm not sure what is the behaviour you expect, but note that `SSE_NONE` is not supported encryption for sync. So the current behaviour is expected, but the error should be definitely handled more gracefully. We'll look into it.

**Comment by jsuchan-reef** [comment]
The command `sync` uses [b2_upload_file](https://www.backblaze.com/apidocs/b2-upload-file) behind the scene, which shows that when encryption is explicitly requested, it will either use `SSE_C` or `SSE_B2` based on the combination of `X-Bz-Server-Side-Encryption-*` headers, there's no way how to explicitly request `SSE_NONE` from the API. The best what can be done in the API is to make this fail loudly before hitting the API.

Sync without encryption can be achieved when the bucket encryption is disabled & `get_setting_for_upload()` will return `None`, in which case the bucket's encryption settings will be used (ie. no encryption).

**Comment by jsuchan-reef** [comment]
> That's nice documentation, thank you. Is it possible that the absence of all X-Bz-Server-Side-Encryption-* headers implies plaintext?

Not really - when the bucket has encryption enabled, omitting the encryption headers works as "use the encryption settings matching the bucket"
