### ISSUE TITLE
test_upload_url_concurrency not in test/ directory

### ISSUE THREAD

**Issue by Hawk777** [Backblaze/b2-sdk-python#471]
I’m not certain if this is intentional or accidental, but `test_upload_url_concurrency` is in the main package source directory rather than the `test/` directory, despite being a test.

**Comment by vbaltrusaitis-reef** [comment]
This file is ancient and it's not a part of the test suite that is run with `nox` or otherwise in CI, it's more of a "test script" than an actual test. It should be either incorporated into the test suite or perhaps simply removed.

**Comment by ppolewicz** [comment]
I don't think anyone used it for many years now.

@Hawk777 since this is your finding, would you like to do the honors?

**Comment by Hawk777** [comment]
You’d like the test deleted?

**Comment by ppolewicz** [comment]
Yes, and the changelog needs to mention it (please see a note about how to use `towncrier`)
