### ISSUE TITLE
Warnings on excluded files

### ISSUE THREAD

**Issue by shacker** [Backblaze/b2-sdk-python#496]
My exclusion regexes are working fine, but I'm getting lots of warnings like:

```
WARNING: /path/to/file could not be accessed (no permissions to read?)
```

That's probably because I ran the script without `sudo` and some dirs are off-limits, but if I've excluded `/path/to`, it shouldn't even be looking at that path, so why the warning?

**Comment by mjurbanski-reef** [comment]
Currently, exclusion happens after iteration of files, so it is indeed suboptimal.

This will likely also cause `b2` CLI to return status code 1 (fail) even if inaccessible are skipped, which makes it not only annoying but a full fledged bug that has to be fixed.

**Comment by shacker** [comment]
Thanks for the fix!
