### ISSUE TITLE
In b2sdk-2.4.0, some files are uploaded redundantly

### ISSUE THREAD

**Issue by titus8** [Backblaze/b2-sdk-python#502]
Good day.

I've discovered a curious issue in b2sdk-2.4.0 that is a regression from b2sdk-2.3.0.

When uploading the tree

        test
        |
        |---- a
        |       |---- foo (a file)
        |
        |---- "a b"
        |       |---- bar (a file)

the first time, _foo_ and _bar_ are uploaded as expected. Subsequent uploads will always upload _bar_, even if the mod time is unchanged. If the directory _a_ is removed, the redundant uploads of _bar_ do not occur.

I've attached a script to reproduce this issue. in issue.py, you will need to set the destination bucket and path appropriately.

I'm using Python 3.12 on a Mac M1 running macOS Sonoma 14.5. I've attached a minimum repro script.

Thanks.

[b2sdk-2.4.0-issue.tgz](https://github.com/user-attachments/files/15894746/b2sdk-2.4.0-issue.tgz)

**Comment by mjurbanski-reef** [comment]
Regression happened in #501 . We expected slight change in synchronization order, but apparently there is was a much more serious side effect that was not detected by tests.

Both regression and tests coverage will be fixed ASAP.
Thank you for nicely described bug report :)

**Comment by mjurbanski-reef** [comment]
Fix published https://github.com/Backblaze/b2-sdk-python/releases/tag/v2.4.1
