### ISSUE TITLE
'upload_local_file' does not respect bucket lifecycle setting

### ISSUE THREAD

**Issue by dwlfrth** [Backblaze/b2-sdk-python#523]
My bucket lifecycle setting is configured to only keep the last version of the file.
When uploading the same file using the 'upload_local_file' method, a version is incremented and all the versions of the file stays in the bucket.

Is this the expected behavior ?

**Comment by dwlfrth** [comment]
Tried with the b2 cli and same behavior

**Comment by ppolewicz** [comment]
The bucket lifecycle setting makes the server hide/delete the files, I think once per day. You _can_ temporarily store multiple versions.

**Comment by dwlfrth** [comment]
Understand.
But why, if I set the lifecycle policy to keep only the latest version, it does so when interacting with the web inteface but not when using API ?
Consistency in the behavior would be great :)

**Comment by ppolewicz** [comment]
Honestly, I don't know. Does the web interface really enforce the lifecycle policy immediately after upload/hide?

**Comment by dwlfrth** [comment]
It does. Using web UI I do not see files versions

**Comment by ppolewicz** [comment]
Web UI doesn't do that. We tried the web UI and I can see the old versions. I'm not sure what you are seeing. Maybe double-check what happens by `ls --long --versions` through the CLI after you create a duplicate file in web ui?

**Comment by dwlfrth** [comment]
You are totally right. My mistake !
All good then ;)
