### ISSUE TITLE
Avoid duplicate keys

### ISSUE THREAD

**Issue by mikkelam** [Backblaze/b2-sdk-python#61]
Hi Author. Thanks a lot for this great SDK. Very easy to setup and use.

I'm wondering how i can avoid uploading duplicated files? 
say i upload a file twice that has same key, is there a way to reject the second upload somehow?

Thanks!

**Comment by ppolewicz** [comment]
Check out [synchronizer](https://b2-sdk-python.readthedocs.io/en/master/api/sync.html) - you can configure it to compare files by modification time (which usually is sufficient for deduplication of backup snapshots). Comparing by hash could be easily added, aldough it would be very CPU-intensive to run it.

If you want to deduplicate the different files with the same content, then I guess you could build a CAS (content-addressable storage) where the filename is equal to the hash of its content and then you would need to manage the index of the files in some other manner, so for example you could put all actual files in a large hidden folder and then have the regular file structure with files actually having just the hash inside, so when reading a named file you would retrieve a hash, and then in the second request you would read the actual content. Deletion becomes a problem in such case though - after a file is deleted from the index you would need to check if any other files still use the same content, before you delete the actual data or not.

And then there is a matter of files having parts that are duplicates and new parts, where file is composed of "chunks", some of which are unique, but not all. There can also be internal duplication. This is a broad subject.

It would really help if you would say something more about what you are trying to build and why :)

I seem to remember that [duplicity](http://duplicity.nongnu.org/) can be integrated with b2 and I think it has variable-size chunk-based deduplication. You can build something like that using b2-sdk-python, but maybe you can just use duplicity?

**Comment by mikkelam** [comment]
Thanks for the elaborate answer. To be clear what I'm trying to accomplish:

Let's say I upload image `plant/<hash>.jpeg`, where hash is some precomputed hash i have made. Now, I'd like to replace the same key at `plant/<hash>.jpeg` if I upload that one twice (let's say i have a fault and I lose track of the original upload, next time this item is uploaded I only have one copy).

I was hoping B2 had an option to preserve unique keys or something similar?

**Comment by ppolewicz** [comment]
do you store (at least a partial) copy of the `plant/` directory on the uploading machine?

**Comment by mikkelam** [comment]
No i'm downloading the images and storing it directly on b2 and then i'm trying to save only the links to b2 items. I was hoping that if some uploaded file was lost, re uploading would overwrite the new one

**Comment by ppolewicz** [comment]
I think you could actually use [sync](https://b2-sdk-python.readthedocs.io/en/master/api/sync.html?highlight=synchronizer#synchronizer) with a properly configured [ScanPoliciesManager](https://github.com/Backblaze/B2_Command_Line_Tool/blob/0a4fc0706d72d41af6266c25f8653f5915e418ce/b2/console_tool.py#L1288) for this with a proper include/exclude, it makes a list of files on local and remote side and only uploads the new file if it differs (in a configurable way - through size or mod time etc). In your case the list would just have one file. You would be executing list_* queries a lot, I'm not sure if it's a problem for you or not.

**Comment by mikkelam** [comment]
Thank you

**Comment by israel-oye** [comment]
> Check out [synchronizer](https://b2-sdk-python.readthedocs.io/en/master/api/sync.html) - you can configure it to compare files by modification time (which usually is sufficient for deduplication of backup snapshots). Comparing by hash could be easily added, aldough it would be very CPU-intensive to run it.
> 
> If you want to deduplicate the different files with the same content, then I guess you could build a CAS (content-addressable storage) where the filename is equal to the hash of its content and then you would need to manage the index of the files in some other manner, so for example you could put all actual files in a large hidden folder and then have the regular file structure with files actually having just the hash inside, so when reading a named file you would retrieve a hash, and then in the second request you would read the actual content. Deletion becomes a problem in such case though - after a file is deleted from the index you would need to check if any other files still use the same content, before you delete the actual data or not.
> 
> And then there is a matter of files having parts that are duplicates and new parts, where file is composed of "chunks", some of which are unique, but not all. There can also be internal duplication. This is a broad subject.
> 
> It would really help if you would say something more about what you are trying to build and why :)
> 
> I seem to remember that [duplicity](http://duplicity.nongnu.org/) can be integrated with b2 and I think it has variable-size chunk-based deduplication. You can build something like that using b2-sdk-python, but maybe you can just use duplicity?

How can one use the synchronizer for just pure upload and download?

**Comment by ppolewicz** [comment]
There is a function in there that generates the tasks to be done and I think you can swap it out for one of your choosing, or you could just use the download and upload manager thread pools without touching sync itself.
