### ISSUE TITLE
'b2' has no attribute 'bucket'

### ISSUE THREAD

**Issue by Gert-P** [Backblaze/b2-sdk-python#70]
When trying to make a backup with benji to backblaze b2 i get this error:

`ERROR: An exception of type AttributeError occurred: module 'b2' has no attribute 'bucket'`

**Comment by ppolewicz** [comment]
Could you please show your output of `pip freeze`? It looks like your environment has a version of `b2-sdk-python`  which is newer than what `b2` (cli) supports.

BTW Benji relies on `b2` (cli), not `b2-sdk-python`

**Comment by Gert-P** [comment]
Thank you for the reply, Here is my output:

argcomplete==1.10.0
arrow==0.13.0
b2==1.4.0
b2sdk==0.1.8
benji==0.4.0
boto3==1.9.214
botocore==1.12.214
Cerberus==1.3.1
certifi==2019.6.16
cffi==1.12.3
chardet==3.0.4
colorama==0.4.1
colorlog==4.0.2
dateparser==0.7.1
diskcache==4.0.0
docutils==0.15.2
funcsigs==1.0.2
idna==2.8
jmespath==0.9.4
logfury==0.1.2
Mako==1.1.0
MarkupSafe==1.1.1
prettytable==0.7.2
psycopg2-binary==2.8.3
pycparser==2.19
pycryptodome==3.8.2
pyparsing==2.4.2
python-dateutil==2.8.0
python-editor==1.0.4
pytz==2019.2
regex==2019.8.19
requests==2.22.0
ruamel.yaml==0.15.100
s3transfer==0.2.1
semantic-version==2.6.0
setproctitle==1.1.10
six==1.12.0
sortedcontainers==2.1.0
sparsebitfield==0.2.2
SQLAlchemy==1.3.7
structlog==19.1.0
tqdm==4.34.0
tzlocal==2.0.0
urllib3==1.25.3
zstandard==0.11.1

**Comment by Gert-P** [comment]
Seems you were correct, the issue has been fixed:

https://github.com/elemental-lf/benji/commit/3725b446022756a345fbdadaa47f386960937611

**Comment by q409640976** [comment]
is there a dome for upload a image?

**Comment by ppolewicz** [comment]
What do you mean by a "dome"?

**Comment by q409640976** [comment]
> What do you mean by a "dome"?

sorry,demo
