### ISSUE TITLE
ERROR: FAILED to upload after 5 tries. Encountered exceptions: Connection error: ('Connection aborted.', BadStatusLine("''",)) 

### ISSUE THREAD

**Issue by spinitron** [Backblaze/b2-sdk-python#74]
The command run from a cron.hourly script was

    b2 sync --noProgress --keepDays 14 /home/data/v2 b2://bhs-backup/ > /dev/null

b2 wrote to stderr

```
ERROR: FAILED to upload after 5 tries. Encountered exceptions: Connection error: ('Connection aborted.', BadStatusLine("''",)) 
Connection error: ('Connection aborted.', BadStatusLine("''",)) 
Broken pipe: unable to send entire request 
Connection error: ('Connection aborted.', error(104, 'Connection reset by peer')) 
Connection error: ('Connection aborted.', error(104, 'Connection reset by peer'))
```

**Comment by spinitron** [comment]
This error was logged twice on Sep 22 and 23

**Comment by ppolewicz** [comment]
This indicates a temporary server-side error encountered in b2-cli. The CLI tried to recover from the error automatically, but those attempts failed too. Further discussion about this is moved to #73.
