### ISSUE TITLE
Transferer v2

### ISSUE THREAD

**Issue by ppolewicz** [Backblaze/b2-sdk-python#77]
We need to significantly alter how uploads are handed in b2sdk to provide better configurability and to properly handle multi-part server side copy.

The logic of uploads is going to be moved to transferer, but it is going to be pretty abstract. The same flow will be used by single part uploads, multi-part uploads, multi-part upload continuation, single-part server side copy, mutli-part server side copy as well as "emerging" - synthesyzing a file out of pieces, some of which are in the cloud already and some are still local and need to be uploaded. The Emerger will be capable of uploading, server-side copying and downloading a stream to then upload it, that's why it is not called an Uploader.

A corner case of that is when we need to download some data to then upload it again (due to server-side lower size limit of part equal currently to 5MB) and another is that sometimes a very large file needs to be copied and Emerge will need to break it down to smaller chunks, otherwise the server-side copy will refuse to handle the request.

The copy operation will have an optional flag, which will terminate the operation if any data would need to be downloaded in order to fulfill the copying (so if it would not be a purely server-side copy). Setting that flag to `True` will force the Emerger to consume the entire iterable to verify whether the operation is a pure copy (unless it is not - then it can exit as soon as a range that cannot be satisfied without downloading is found).

There will be two thread pools, one for uploading and another one for downloading. This is to avoid deadlocks when we'd need to download data in order to upload it back and all threads in the pool are busy doing that (waiting for someone to download the data). Since downloads will never wait for uploads (in the current design), two threadpools will ensure we avoid a deadlock.

To decrease the final PR size, we'll move the upload logic as is to transferer first. We'll implement b2_copy_part support in raw_api as well as in the simulator. Some tests can maybe be added before the feature is actually implemented.

The part of code which decides how to split a file into parts is going to have a simple implementation - it is a very hard problem to optimize and we are not going to spend a lot of effort on the strategy at this point. This may cause some copy operations which could be completed with just upload+copy to not be properly recognized, so if the `forbid_downloads` flag is set to `True`, we may return failure because of an imperfect strategy. This is a known limitation of the design and we will be open for pull requests from anyone wishing to optimize this further (as long as it doesn't degrade the performance of the naiive approach (too much)).

In Transferer we already delegate some functionality away to Downloaders. This is nice because Transferer class itself is smaller. Here the functionality will be moved to a new class, called Emerger. Emerger, in its main operation, will need to accept an iterable of RangeToEmerge objects, which may be:
- a range of a remote file (possibly the entire file)
- a range of a local file (possibly the entire file)
- an unfinished upload part (in case we are continuing an interrupted upload)

but those can be mixed. Sometimes a file will be present both on the cloud and on the local filesystem and Emerger will decide whether to use the local part or download it. A range may be present on the cloud in multiple objects at different locations and maybe the same applies to the local side too, but optimization of local reading to maximize streaming is not the goal at this point. Therefore the interface will NOT allow the user to provide multiple locations of a range of the same type (cloud, local, unfinished part). Our API interface policy allows us to easily add such support in the future without breaking interface compatibility for the existing users, so we'll match the interface with the current implementation plan and will change the interface if it's ever required.

Transferer will provide a few wrappers for Emerger, allowing the user to easily:
- upload a local file (that's just a single RangeToEmerge with local file source and nothing else, (which may be broken down by the Emerger if the file is large))
- server-side copy a file (that's just a single RangeToEmerge without local file source)

Both of those operations may break an operation into smaller ones. There are no plans to allow for forcing a file to be treated as small or large, for upload or for server-side copy. If someone would need this (though I can't imagine why), the function would be easy to add by swapping out Emerger to another implementation (so one would have to pass it to an explicitly constructed Transferer, which would be passed to B2Api).

When a piece of a file needs to be downloaded from the cloud so that we can upload it again (simplest case being a "copy" request of two remote-only ranges at least one of which is less than 5MB), we will NOT save it into a temporary storage on the local drive, but we'll pipe it directly through to the uploading thread. Local storage would be tricky to configure and may not be expected by the user, may cause security issues etc, but streaming also has its issues - if downloading is faster than uploading, we may have a memory utilization issue. Therefore care will need to be taken to avoid exploding memory in case of asymmetric network performance.

This issue is now open for comments on the design, so that we can improve the concept before a significant amount of work is put into implementation.

**Comment by bwbeach** [comment]
This is good.  It looks like what we've talked about in the past, and I like the structure.

It's not stated explicitly, but it sounds like the Downloader will continue to be separate from the Emerger.

I think there may be a fourth case of RangeToEmerge that might be useful in some applications: a byte string in memory.

There may be a corner case when using "an unfinished upload part".  I think there's a problem if I give the Emerger two things: (1) A one-byte range of a local file, and (2) an unfinished upload part.  Because b2 won't allow a one-byte part, the existing unfinished part cannot be used.  If the RangeToEmerge object also has the source of the unfinished part, it could fall back to that and re-upload the data if needed.

What part size will be the target?  The service returns `recommendedPartSize` and `absoluteMinimumPartSize`.  The Emerger should use the `recommendedPartSize`, unless it needs smaller parts to avoid downloading data.

**Comment by ppolewicz** [comment]
We will use the existing upload source abstraction for RangeToEmerge local file, so it will be a byte range in memory, local file, or something else as defined by the user.

Downloader will be a sibling of Emerger in the Transferer family.

That corner case is very interesting indeed!

We'll use https://github.com/Backblaze/b2-sdk-python/blob/335f225ef69b8cfdd5ad9bc41866c113688b0307/b2sdk/account_info/sqlite_account_info.py#L336 as in the past, when possible, but I think we might need to start parsing and using `absoluteMinimumPartSize` too for the emerge planner to produce reasonable plans.

**Comment by ppolewicz** [comment]
After further review of the design, a new signature of Emerger "main" interface is being considered, whereas the source would be a **sorted** iterator of (possibly overlapping) source ranges of various types. This improves over the original proposal in the opening post, where a burden of some input data pre-processing was on the user. An example situation is described below.

Lets imagine a situation where we have:
- range A-C in the cloud
- range B-E on local drive
- range D-F in the cloud

like this:
```
A          C       D           G 
|          |       |           | 
| cloud-AC |       | cloud-DG  | 
|          |       |           | 
v          v       v           v 
############       ############# 
^                              ^ 
|                              | 
+---- desired file A-G --------+ 
|                              | 
|                              | 
|    ######################### | 
|    ^                       ^ | 
|    |                       | | 
|    |      local file-BF    | | 
|    |                       | | 
A    B     C       D       E F G
```
where in the opening post design, user would need to break down the ranges artificially do indicate unique ranges of A-B, B-C, C-D, D-E, E-F and F-G passing 6 ranges in while only having 3 actual sources.
In the new design the ranges will be A-C, B-F and D-G.

**Comment by ppolewicz** [comment]
Additionally, an artificial source object of a zero-length range with no actual sources anywhere is considered to be used as a way for the iterator to tell Emerger that no further sources for the already provided ranges will be provided, as a synchronization point, to let Emerger formulate and start executing a plan of actual upload.
